poll/urls.py
#coding:utf8
from django.conf.urls import include, url
import views

urlpatterns = [
    url(r'^$', views.index ,name='index'),
    url(r'^(?P<qid>\d+)/$', views.detail ,name='detail'), # 投票详情页（包括投票选项）
    url(r'^results/(?P<qid>\d+)/$', views.resuls ,name='results'), # 投票结果
    url(r'^votes/(?P<qid>\d+)/$', views.vote ,name='votes'), # 投票操作
]

polls/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('poll.urls',namespace='poll')),
]

poll/models.py
#coding:utf8
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=30)
    pub_date = models.DateTimeField(verbose_name='发起时间')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.boolean = True
    was_published_recently.short_description = '是否最近一天发起?'

    def __unicode__(self): # python3是 __str__
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question)

    def __unicode__(self):
        return self.choice_text

poll/views.py
#coding:utf8
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,get_object_or_404
from models import Question,Choice
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list':latest_question_list}
    return render(request,'poll/index.html',context)
    # output = '<br>'.join([p.question_text for p in latest_question_list])
    # print type(output)
    # return HttpResponse('欢迎来到千峰在线投票!!!<hr>' + output.encode('utf-8'))

def detail(request,qid):
    question = get_object_or_404(Question,pk=qid)
    context = {'question' : question}
    return render(request,'poll/detail.html',context)

    # return HttpResponse('你正在投票详情页，投票id是%s' % str(qid))

def resuls(request,qid):
    # return HttpResponse('你正在投票结果页，投票id是%s' % str(qid))
    question = get_object_or_404(Question, pk=qid)
    return render(request,'poll/results.html',{'question':question})

def vote(request,qid):
    # return HttpResponse('你正在投票，投票id是%s' % str(qid))
    p = get_object_or_404(Question,pk=qid)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'poll/detail.html',{
            'question' : p,
            'error_message' : '请选择一个选项',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results',args=(qid,)))

poll/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票详情</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{#<ul>#}
{#    {% for choice in question.choice_set.all %}#}
{#        <li>{{ choice.choice_text }}</li>#}
{#        {% empty %}#}
{#        <p>暂无选项</p>#}
{#    {% endfor %}#}
{#</ul>#}
<form action="{% url 'poll:votes' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" value="{{ choice.id }}" />
        <label>{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="投票">
</form>
<hr>
<h1 style="color: #ff0000">{{ error_message }}</h1>
</body>
</html>

poll/templates/poll/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>缥缈峰投票</title>
</head>
<body>
<h1>缥缈峰投票</h1>
<ul>
{% for question in latest_question_list %}
    <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% empty %}
    <p>还没有投票！！！敬请期待</p>
{% endfor %}
</ul>
</body>
</html>

poll/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>千峰投票</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}-----{{ choice.votes }} vote{{ choice.votes | pluralize }}</li>
    {% endfor %}
</ul>
</body>
</html>